version: '3.1'

services:

  elasticsearch:
    image: elasticsearch:5.5.2
    volumes:
      - ./data/elasticearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200        

  kibana:
    image: kibana:5.5.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200    


volumes:
  elasticsearch:
